version: '3.8'

services:
  telegram-bot:
    build:
      context: ./telegram-bot
    container_name: telegram-bot
    ports:
      - "8080:8080"
    environment:
      - telegram.bot.token=${TELEGRAM_BOT_TOKEN}
      - telegram.bot.username=${TELEGRAM_BOT_USERNAME}
      - imagerenderer.url=${IMAGE_RENDERER_URL}
    networks:
      - selenoid-network

  image-renderer:
    build:
      context: ./image-renderer
    container_name: image-renderer
    ports:
      - "8081:8081"
    volumes:
      - ./image-renderer-screenshots:/build/reports/tests
    networks:
      - selenoid-network

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: [
      "-limit", "5",
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video",
      "-container-network", "selenoid-network"
    ]
    networks:
      - selenoid-network

networks:
  selenoid-network:
    driver: bridge
