version: '3.8'

services:
  telegram-bot:
    build:
      context: ./telegram-bot
    container_name: telegram-bot
    ports:
      - "8080:8080"
    environment:
      - telegram.bot.token=${TELEGRAM_BOT_TOKEN}
      - telegram.bot.username=${TELEGRAM_BOT_USERNAME}
      - imagerenderer.url=${IMAGE_RENDERER_URL}
      - git.repo.url=${GIT_REPO_URL}
    networks:
      - selenoid-network

  image-renderer:
    build:
      context: ./image-renderer
    container_name: image-renderer
    ports:
      - "8081:8081"
    volumes:
      - ./image-renderer-screenshots:/build/reports/tests
    networks:
      - selenoid-network

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command:
      [
        "-limit", "5",
        "-conf", "/etc/selenoid/browsers.json",
        "-video-output-dir", "/opt/selenoid/video",
        "-container-network", "selenoid-network"
      ]
    networks:
      - selenoid-network

  jmeter:
    image: justb4/jmeter:5.6.2
    container_name: jmeter
    environment:
      - DOMAIN=${JMETER_DOMAIN}
      - PORT=${JMETER_PORT}
      - THREADS=${JMETER_THREADS}
    volumes:
      - ./jmeter:/testplan
    networks:
      - selenoid-network
    command: sleep infinity

networks:
  selenoid-network:
    external: true
