name: Java CI

on:
  push:
    branches: [ develop ]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Настроить JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Собрать и запустить проект
        run: |
          cd ./telegram-bot
          echo "Текущая директория: $(pwd)"
          mvn clean package -DskipTests
          docker build -t your-app .
          docker run -d -p 8080:8080 your-app
