name: Java CI/CD for Microservices

on:
  push:
    branches: [ develop ]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Настроить JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Собрать проекты (Maven)
        run: |
          cd telegram-bot
          mvn clean package -DskipTests
          cd ../image-renderer
          mvn clean package -DskipTests
          cd ..

      - name: Собрать образы Docker
        run: |
          docker-compose build

      - name: Остановить старые контейнеры (если есть)
        run: |
          docker-compose down || true

      - name: Запустить новые контейнеры
        run: |
              export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
              export TELEGRAM_BOT_USERNAME=${{ secrets.TELEGRAM_BOT_USERNAME }}
              export IMAGE_RENDERER_URL=${{ secrets.IMAGE_RENDERER_URL }}
              docker-compose up -d
