name: Java CI

on:
  push:
    branches: [ develop ]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Настроить JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Собрать проект и создать Docker-образ
        run: |
          cd ./telegram-bot
          echo "Текущая директория: $(pwd)"
          mvn clean package -DskipTests
          docker build -t tgbot .

      - name: Остановить старый контейнер (если есть)
        run: |
          docker stop your-app || true
          docker rm your-app || true
          docker stop tgbot || true
          docker rm tgbot || true

      - name: Запустить новый контейнер
        run: |
          docker run -d --name tgbot -p 8080:8080 \
          -e telegram.bot.token=${{ secrets.TELEGRAM_BOT_TOKEN }} \
          -e telegram.bot.username=${{ secrets.TELEGRAM_BOT_USERNAME }} \
          your-app
