name: Java CI/CD for Microservices

on:
  push:
    branches: [ develop ]

jobs:
  build-and-run:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: self-hosted


    steps:
      - name: Очистить рабочую директорию и сбросить права
        run: |
          sudo rm -rf ${{ github.workspace }}/*
        continue-on-error: true

      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Настроить JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Собрать проекты (Maven)
        run: |
          cd telegram-bot
          mvn clean package -DskipTests
          cd ../image-renderer
          mvn clean package -DskipTests
          cd ..

      - name: Собрать образы Docker
        run: |
          docker pull seleniarm/standalone-firefox
          docker-compose build

      - name: Создать сеть для Selenoid (если ещё нет)
        run: |
          docker network create selenoid-network || true

      - name: Остановить старые контейнеры и почистить систему
        run: |
          docker-compose down || true

      - name: Запустить новые контейнеры
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
          IMAGE_RENDERER_URL: ${{ secrets.IMAGE_RENDERER_URL }}
          GIT_REPO_ATP_URL: ${{ secrets.GIT_REPO_ATP_URL }}
          GIT_REPO_TESTPROJECT_URL: ${{ secrets.GIT_REPO_TESTPROJECT_URL }}
          CHAOS_MONKEY_URL: ${{ secrets.CHAOS_MONKEY_URL }}
        run: |
          docker-compose up -d
