name: Java CI/CD for Microservices

on:
  push:
    branches: [ develop ]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Настроить JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Собрать проекты (Maven)
        run: |
          cd telegram-bot
          mvn clean package -DskipTests
          cd ../image-renderer
          mvn clean package -DskipTests
          cd ..

      - name: Собрать образы Docker
        run: |
          docker-compose build

      - name: Остановить старые контейнеры и почистить систему
        run: |
          docker-compose down || true
          docker system prune -af --volumes || true

      - name: Запустить новые контейнеры
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
          IMAGE_RENDERER_URL: ${{ secrets.IMAGE_RENDERER_URL }}
        run: |
          docker-compose up -d
