name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: self-hosted
    # Использование тега для выбора конкретного раннера
    if: ${{ github.event.repository.owner.id == 12345 && contains(github.event.repository.permissions.admin, 'true') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t your-app .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 your-app
